[package]
name = "clipper"
version = "0.1.0"
edition = "2024"

[lib]
name = "marina"
path = "src/lib.rs"

[dependencies]

[profile.release]
strip = false  # Disable symbol stripping to avoid rust-objcopy LLVM.dylib warning
